### ISSUE TITLE
Enhancing Workflow with GitHub Actions

### ISSUE THREAD

**Issue by mitshelle** [munch2024/munch#67]
Previously, the workflow only had some automations. It can be improved to provide more benefits that will make the life of a developer easier. 

The workflow already does multiple things like linting, installing dependencies, and running nosetests. These are very much needed, but the it is not fully utilized. 

Goals for Refactoring: 
1. add notification for errors
2. add performance testing

For future enhancements, things like automatic builds and server deployments would be amazing!

Below is the workflow before enhancements. 

```yml
name: CI workflow

on: 
    push:
        branches: ["main"]
    pull_request: 
        branches: ["main"]


jobs:
    build:
        runs-on: ubuntu-latest
        container: python:3.9-slim
        steps: 
            - name: Checkout
              uses: actions/checkout@v4
            - name : Install dependencies
              run: | 
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Lint with flake8
              run: | 
                flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
                flake8 src --count --max-complexity=10 --max-line-length=127 --statistics
            - name: Run unit tests with nose
              run:
                nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
                
```
